version: '3.8'
services:
  nodo1:
    build: ./nodo
    ports:
      - "3000:3000"
    environment:
      - CONFIG_FILE=config/nodo1_config.json

  nodo2:
    build: ./nodo
    ports:
      - "3001:3000"
    environment:
      - CONFIG_FILE=config/nodo2_config.json

  sensor1:
    build: ./sensor
    ports:
      - "5000:5000"
    environment:
      - SENSOR_ID=sensor1
      - MAQUINA_ID=maquina1

  sensor2:
    build: ./sensor
    ports:
      - "5001:5000"
    environment:
      - SENSOR_ID=sensor2
      - MAQUINA_ID=maquina1