# Use an official Python image as the base image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the sensor simulation script
COPY . .

# Set the command to run the sensor simulation
CMD ["python", "./sensor_simulation.py"]
